### ISSUE TITLE
Presets as Effect Switch in HomeKit

### ISSUE THREAD

**Issue by derpate1989** [jstrausd/homebridge-simple-wled#34] opened 2022-01-14 13:30 UTC
Hallo,

I have set many preset with my favorite Color, brightness and Effect Speed. 

It is possible to integrate the self made preset as effect switch in HomeKit? 

Best regards

**Comment by ddcreation** [comment] 2023-04-19 09:35
Duplicate of https://github.com/jstrausd/homebridge-simple-wled/issues/16, maybe we can close this one?

**Comment by mkormendy** [comment] 2024-03-07 19:50
This can be closed.

**Closed** 2024-03-08 04:57 UTC
